# Podfile

# Select the appropriate platform below
platform :ios
# platform :osx

#
# Some other entries might already exist in the file
# ...
#

target :EventKitTests, :exclusive => true do
	pod 'Kiwi', :head
end
